defaults:
  - geobench

benchmark_name: classification_v1.0
dataset_name: m-eurosat
task: classification
band_names:
  - "01 - Coastal aerosol"
  - "02 - Blue"
  - "03 - Green"
  - "04 - Red"
  - "05 - Vegetation Red Edge"
  - "06 - Vegetation Red Edge"
  - "07 - Vegetation Red Edge"
  - "08 - NIR"
  - "08A - Vegetation Red Edge"
  - "09 - Water vapour"
  - "10 - SWIR - Cirrus"
  - "11 - SWIR"
  - "12 - SWIR"
num_classes: 10
multilabel: false
num_channels: 13
band_wavelengths:
  - 440
  - 490
  - 560
  - 665
  - 705
  - 740
  - 783
  - 842
  - 860
  - 940
  - 1370
  - 1610
  - 2190

