defaults:
  - base_dataset

dataset_type: corine
task: classification
dataset_name: spectral_earth # for band_ids
num_classes: 19
num_channels: 8
data_path: ${oc.env:DATASETS_DIR}/spectral_earth
image_resolution: 224
multilabel: true
full_spectra: true # for wavelengths_mean_nm and wavelengths_sigma_nm

# Target dataset
target_dataset_name: dummy-superdove